name: Deploy Cloud Run via Terraform

on:
  push:
    branches:
      - main
      - uat
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init

      - name: Select Environment
        id: envselect
        run: |
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "tfvars=environments/dev.tfvars" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF_NAME}" == "uat" ]]; then
            echo "tfvars=environments/uat.tfvars" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF_NAME}" == "prod" ]]; then
            echo "tfvars=environments/prod.tfvars" >> $GITHUB_OUTPUT
          else
            echo "Branch not mapped to environment"
            exit 1
          fi

      - name: Terraform Plan
        run: terraform plan -var-file=${{ steps.envselect.outputs.tfvars }}

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=${{ steps.envselect.outputs.tfvars }}
